SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SET SERVEROUTPUT ON;

SELECT EXTRACT(MONTH FROM TO_DATE(RECORD_DATE))
				,MAX(DATA_VALUE) AS MAX_ 
				,MIN(DATA_VALUE) AS MIN_
				,ROUND(AVG(CASE WHEN DATA_TYPE = 'avg' THEN DATA_VALUE ELSE NULL END),0) AS AVG_
FROM TEMPERATURE_RECORDS
WHERE EXTRACT(MONTH FROM TO_DATE(RECORD_DATE)) BETWEEN 7 AND 12
GROUP BY EXTRACT(MONTH FROM TO_DATE(RECORD_DATE))
ORDER BY EXTRACT(MONTH FROM TO_DATE(RECORD_DATE))
;




exit;