SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SET SERVEROUTPUT ON;

SELECT T.*
FROM (SELECT
    A.CUSTOMER_ID, A.NAME
    ,CONCAT(CONCAT('+',B.COUNTRY_CODE),A.PHONE_NUMBER) AS COUNTRYPHONE_CODE
FROM CUSTOMERS A 
LEFT JOIN COUNTRY_CODES B
ON A.COUNTRY = B.COUNTRY
) T
ORDER BY T.CUSTOMER_ID;

exit;