SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SET SERVEROUTPUT ON;

SELECT
    A.STOCK_CODE
FROM PRICE_TODAY A
LEFT JOIN PRICE_TOMORROW B
ON A.STOCK_CODE = B.STOCK_CODE
WHERE A.PRICE < B.PRICE
ORDER BY 1 ASC;
exit;