SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SET SERVEROUTPUT ON;



SELECT A.USER_ACCOUNT_ID
    ,C.FIRST_NAME, C.LAST_NAME
    , A.CUSTOMER_ID
    ,B.CUSTOMER_NAME
    , A.CNT
FROM (SELECT USER_ACCOUNT_ID, CUSTOMER_ID, COUNT(*) CNT
        FROM  CONTACT 
        GROUP BY USER_ACCOUNT_ID, CUSTOMER_ID) A
LEFT JOIN CUSTOMER B
ON A.CUSTOMER_ID = B.ID
LEFT JOIN USER_ACCOUNT C
ON A.USER_ACCOUNT_ID = C.ID
WHERE A.CNT > 1
ORDER BY 1 ASC;

exit;