SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SET SERVEROUTPUT ON;


SELECT A.CITY_NAME, E.PRODUCT_NAME
    , ROUND(SUM(D.LINE_TOTAL_PRICE),2) SUM_AMT
FROM CITY A, CUSTOMER B, INVOICE C, INVOICE_ITEM D, PRODUCT E
WHERE A.ID = B.CITY_ID
    AND B.ID = C.CUSTOMER_ID
    AND C.ID = D.INVOICE_ID
    AND D.PRODUCT_ID = E.ID
GROUP BY A.CITY_NAME, E.PRODUCT_NAME
ORDER BY SUM(D.LINE_TOTAL_PRICE) DESC, A.CITY_NAME, E.PRODUCT_NAME ASC;


SELECT DISTINCT COUNTRY_NAME, TOTAL_INVOICE, ROUND(AVG_AMT_COUNTRY, 6) AS AVG_AMT_COUNTRY
FROM (
SELECT AVG(CAST(T.TOTAL_PRICE AS FLOAT))  OVER(PARTITION BY COUNTRY_NAME) AS AVG_AMT_COUNTRY
    ,AVG(CAST(T.TOTAL_PRICE AS FLOAT)) OVER() AS AVG_AMT_TOTAL
    ,T.COUNTRY_NAME
    ,COUNT(T.INVOICE_NUMBER) OVER(PARTITION BY COUNTRY_NAME) AS TOTAL_INVOICE
FROM
    (SELECT C.COUNTRY_NAME , A.TOTAL_PRICE, A.INVOICE_NUMBER
    FROM CUSTOMER B 
    RIGHT JOIN INVOICE A
    ON A.CUSTOMER_ID = B.ID
    LEFT JOIN (SELECT A.ID, B.COUNTRY_NAME
        FROM CITY A
        RIGHT JOIN COUNTRY B
        ON A.COUNTRY_ID = B.ID) C
    ON B.CITY_ID = C.ID) T)
    WHERE AVG_AMT_COUNTRY > AVG_AMT_TOTAL;

    
exit;

